fun main(){
    AndGate2(Output())
        .e1(true)
        .e2(false)
        .construiestePoarta()

    AndGate3(Output())
        .e1(true)
        .e2(true)
        .e3(true)
        .construiestePoarta()

    AndGate4(Output())
        .e1(true)
        .e2(true)
        .e3(true)
        .e4(true)
        .construiestePoarta()

    AndGate8(Output())
        .e1(false)
        .e2(false)
        .e3(true)
        .e4(false)
        .e5(false)
        .e6(false)
        .e7(true)
        .e8(false)
        .construiestePoarta()
}